import Foundation

public enum AgentBuiltinToolID {
  public static let searchTools = "william.tools.search"
  public static let activateToolGroup = "william.tools.activate"
  public static let runCode = "william.tools.code.run"
  public static let createSkill = "william.tools.skill.create"
  public static let fileSystem = "william.filesystem.operate"
  public static let networkAccess = "william.network.access"
  public static let inspectSession = "william.app.session.inspect"
  public static let renameSession = "william.app.session.rename"
  public static let listSessions = "william.app.sessions.list"
  public static let searchConversation = "william.app.conversation.search"
  public static let searchMemory = "william.memory.search"
  public static let listMemories = "william.memory.list"
  public static let remember = "william.memory.remember"
  public static let updateMemory = "william.memory.update"
  public static let forgetMemory = "william.memory.forget"
  public static let listModels = "william.app.models.list"
  public static let setSessionModel = "william.app.session.set_model"
  public static let inspectRuntime = "william.app.runtime.inspect"
  public static let inspectSettings = "william.app.settings.inspect"
  public static let loadInstructionReference = "william.instructions.reference.load"
  public static let createInstructionSkill = "william.instructions.skill.create"
  public static let updateInstructionSkill = "william.instructions.skill.update"
  public static let searchInstructionSkills = "william.instructions.skill.search"
  public static let validateInstructionSkill = "william.instructions.skill.validate"
  public static let disableInstructionSkill = "william.instructions.skill.disable"
  public static let requestLocalAppAction = "william.app.user_action"
  public static let inspectCodeWorkspace = "william.code.workspace.inspect"
  public static let listCodeWorkspaces = "william.code.workspaces.list"
  public static let searchCode = "william.code.search"
  public static let snapshotCodeWorkspace = "william.code.workspace.snapshot"
  public static let diffCodeWorkspace = "william.code.workspace.diff"
  public static let incrementalWriteCode = "william.code.write.incremental"
  public static let listCodeFiles = "william.code.files.list"
  public static let readCodeFile = "william.code.file.read"
  public static let replaceCodeText = "william.code.file.edit"
  public static let registerApp = "william.app.register"
  public static let listApps = "william.apps.list"
  public static let openApp = "william.app.open"
  public static let runAppCommand = "william.app.command"
  public static let inspectAppUI = "william.app.ui.inspect"
  public static let actOnAppUI = "william.app.ui.act"
  public static let waitForAppUI = "william.app.ui.wait"
  public static let screenshotAppUI = "william.app.ui.screenshot"
  public static let runAppUITest = "william.app.ui.test.run"
  public static let inspectKernelPlugins = "william.kernel.inspect"
  public static let kernelPluginLifecycle = "william.kernel.lifecycle"
  public static let authorKernelPlugin = "william.kernel.author"
  public static let communityPlugins = "william.plugins.community"
  /// Not a callable tool. Records an announce-only model turn as a typed
  /// `function_call_output` so hosted converters keep it on the next request.
  public static let runtimeAnnounce = "william.runtime.announce"
}
